# Continuous Integration Workflow
# Runs on every push and pull request to validate builds and tests

name: CI - Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Build API and Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: |
        cd TerminplanerApi
        dotnet restore

    - name: Build API
      run: |
        cd TerminplanerApi
        dotnet build --configuration Release --no-restore

    - name: Run tests
      run: |
        dotnet test TerminplanerApi.Tests/TerminplanerApi.Tests.csproj --configuration Release --no-build --verbosity normal

    - name: Format check
      run: |
        cd TerminplanerApi
        dotnet format --verify-no-changes --verbosity diagnostic
      continue-on-error: true
