name: Sync Labels

# This workflow ensures all required labels exist in the repository
# Triggered on pushes to main or can be run manually

'on':
  push:
    branches:
      - main
    paths:
      - '.github/labels.yml'
      - '.github/workflows/labels.yml'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  sync-labels:
    name: Sync Repository Labels
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Sync labels
        uses: EndBug/label-sync@v2
        with:
          config-file: .github/labels.yml
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-other-labels: false
          # Set to true only if you want to remove labels not in the config
